version: '2.1'
services:

  #
  # edu.chat.demoChat.janus-gateway
  #
  janus-gateway:
    image: 'canyan/janus-gateway:latest'
    command: ["/usr/local/bin/edu.chat.demoChat.janus", "-F", "/usr/local/etc/edu.chat.demoChat.janus"]
    ports:
      - "8188:8188"
      - "8088:8088"
      - "8889:8889"
      - "8000:8000"
      - "7088:7088"
      - "7089:7089"
    volumes:
      - "./.conf/edu.chat.demoChat.janus/edu.chat.demoChat.janus.plugin.audiobridge.jcfg:/usr/local/etc/edu.chat.demoChat.janus/edu.chat.demoChat.janus.plugin.audiobridge.jcfg"
    restart: always