version: '3.8'
services:
  janus-gateway:
    image: 'canyan/janus-gateway:latest'
    command: ["/usr/local/bin/janus", "-F", "/usr/local/etc/janus"]
    ports:
      - "8188:8188"
      - "8088:8088"
      - "8889:8889"
      - "8000:8000"
      - "7088:7088"
      - "7089:7089"
    volumes:
      - "./data/conf/janus/janus.jcfg:/usr/local/etc/janus/janus.jcfg"
      - "./data/conf/janus/janus.plugin.audiobridge.jcfg:/usr/local/etc/janus/janus.plugin.audiobridge.jcfg"
    restart: always

  app:
    build: .
    depends_on:
      - janus-gateway
    ports:
      - "8080:8080"

  frontend:
    restart: unless-stopped
    image: staticfloat/nginx-certbot
    ports:
      - 9090:9090/tcp
      - 443:443/tcp
    environment:
      CERTBOT_EMAIL: step.ponomarev@gmail.com
      # variable names are space-separated
      ENVSUBST_VARS: FQDN
      FQDN: example.com
    volumes:
      - "./data/conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./data/certbot/conf:/etc/letsencrypt"
  volumes:
    letsencrypt:

#  proxy:
#    image: nginx
#    volumes:
#      - "./data/conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
#      - "./data/certbot/conf:/etc/letsencrypt"
#      - "./data/certbot/www:/var/www/certbot"
#    ports:
#      - "9090:9090"
#      - "8443:8443"
#    depends_on:
#      - certbot
#
#  certbot:
#    image: certbot/certbot
#    volumes:
#      - "./data/certbot/conf:/etc/letsencrypt"
#      - "./data/certbot/www:/var/www/certbot"