name: Deploy workflow
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Building
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8

        uses: actions/setup-java@v1
        with:
          java-version: '14'

      - name: Build with Maven
        run: mvn install

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_IP }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH }}
          rm: true
          target: "/home/azureuser"
          source: "target/"
