name: Deploy workflow
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Building
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8

        uses: actions/setup-java@v1
        with:
          java-version: '14'

      - name: Build with Maven
        run: mvn clean && mvn install

      - name: Copy neded files
        run: cp Dockerfile ./target && cp docker-compose.yml ./target && cp -r data target

      - name: Copy single file to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: target
          remote: home/azureuser/app
          host: ${{ secrets.DEPLOY_IP }}
          username: ${{ secrets.DEPLOY_USER }}
          privateKey: ${{ secrets.DEPLOY_SSH }}
