name: Deploy workflow
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Building
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8

        uses: actions/setup-java@v1
        with:
          java-version: '14'

      - name: Build with Maven
        run: mvn clean && mvn install && cp Dockerfile ./target && cp docker-compose.yml ./target

      - name: Create ssh file
        run: touch ssh.pem && echo ${{ secrets.DEPLOY_SSH }} >> ssh.pem

      - name: copy file via ssh password
        run: scp -i ./ssh.pem -r ./target ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_IP }}:/home/azureuser
